
```{r}
source("http://raw.githubusercontent.com/cwendorf/easiDev/main/source-easiDev.R")
```

## One Way Data

```{r}
Factor <- c(rep(1, 10), rep(2, 10), rep(3, 10))
Factor <- factor(Factor, levels = c(1, 2, 3), labels = c("Level1", "Level2", "Level3"))
Outcome <- c(6, 8, 6, 8, 10, 8, 10, 9, 8, 7, 7, 13, 11, 10, 13, 8, 11, 14, 12, 11, 9, 16, 11, 12, 15, 13, 9, 14, 11, 10)
OneWayData <- construct(Factor, Outcome)
```

```{r}
(Outcome~Factor) |> describeMoments() |> print(digits=4)

(Outcome~Factor) |> estimateSet()
(Outcome~Factor) |> focus(Level1, Level2) |> estimateSet() |> print(digits=5)

(Outcome~Factor) |> focus(Level1, Level2) |> estimateDifference()
(Outcome~Factor) |> focus(Level1, Level3) |> estimateComparison()

(Outcome~Factor) |> estimateContrast(c(-1, .5, .5)) |> print(digits=5)
(Outcome~Factor) |> estimateSubsets(c(-1, .5, .5))
(Outcome~Factor) |> plotSubsets(c(-1, .5, .5))
```

```{r}

describe <- describeMoments

estimate <- function(x, contrast = NULL, ...) {
  howmany <- nrow(describeMoments(x))
  if (!is.null(contrast)) {
    estimateSubsetsMeans(x, contrast = contrast, ...)
  } else if (howmany == 2) {
    estimateComparisonMeans(x, ...)
  } else {
    estimateSetMeans(x, ...)
  }
}

graph <- function(results, add = FALSE, ...) {
  out <- results
  if (length(results) == 1) {
    results[[1]] <- results[[1]][, c(1, (ncol(results[[1]]) - 1):ncol(results[[1]]))]
    if (!add) .plotMain(results, ...)
    .intervalsMain(results, ...)
  }
  if (length(results) == 2 && nrow(results[[1]] != nrow(results[[2]]))) {
    results <- .collapseList(results)
    results[[1]] <- results[[1]][, c(1, (ncol(results[[1]]) - 1):ncol(results[[1]]))]
    if (!add) .plotComp(results, ...)
    .intervalsComp(results, ...)
  }
  invisible(out)
}

```

```{r}
(Outcome~Factor) |> describe() |> focus(Level1, Level2) |> estimate() |> graph()

(Outcome~Factor) |> estimate()
(Outcome~Factor) |> focus(Level1, Level3) |> estimate()
(Outcome~Factor) |> focus(Level1, Level3) |> estimate() |> graph()
(Outcome~Factor) |> estimate(contrast=c(-1, .5, .5))


```

## One Way Summary

```{r}
Level1 <- c(N = 10, M = 8.000, SD = 1.414)
Level2 <- c(N = 10, M = 11.000, SD = 2.211)
Level3 <- c(N = 10, M = 12.000, SD = 2.449)
OneWaySummary <- construct(Level1, Level2, Level3, class = "bsm")
```

```{r}
(OneWaySummary)
(OneWaySummary) |> print(digits=4,width=12)

(OneWaySummary) |> focus(Level1, Level2) |> estimateSet()

(OneWaySummary) |> focus(Level1, Level2) |> estimateSet() |> print(digits=2,width=10)
(OneWaySummary) |> focus(Level1, Level2) |> plotSet(digits=2)

(OneWaySummary) |> focus(Level1, Level2) |> estimateDifference()
(OneWaySummary) |> focus(Level1, Level2) |> estimateComparison()
(OneWaySummary) |> focus(Level1, Level2) |> plotComparison()

(OneWaySummary) |> estimateContrast(c(-1, .5, .5))
(OneWaySummary) |> estimateSubsets(c(-1, .5, .5))
(OneWaySummary) |> plotSubsets(c(-1, .5, .5))


(OneWaySummary) |> describe() |> focus(Level1, Level2) |> estimate() |> graph()


```

## Repeated Data

```{r}
Outcome1 <- c(6, 8, 6, 8, 10, 8, 10, 9, 8, 7)
Outcome2 <- c(7, 13, 11, 10, 13, 8, 11, 14, 12, 11)
Outcome3 <- c(9, 16, 11, 12, 15, 13, 9, 14, 11, 10)
RepeatedData <- construct(Outcome1, Outcome2, Outcome3)
```

```{r}
(RepeatedData)
(RepeatedData) |> describeMoments() |> print(digits=2,width=10,main="tough")
(RepeatedData) |> describeCorrelations() |> print(digits=6)

(RepeatedData) |> estimateSet()
(RepeatedData) |> plotSet()
(RepeatedData) |> focus(Outcome1) |> estimateSet()
(RepeatedData) |> focus(Outcome1) |> plotSet(main="Single")

(RepeatedData) |> focus(Outcome1, Outcome2) |> estimateDifference()
(RepeatedData) |> focus(Outcome1, Outcome2) |> plotDifference()

(RepeatedData) |> focus(Outcome1, Outcome2) |> estimateComparison() |> print(digits=6,main=c("cool","cooler"))
(RepeatedData) |> focus(Outcome1, Outcome2) |> plotComparison()

(RepeatedData) |> estimateContrast(c(-1, .5, .5))
(RepeatedData) |> estimateSubsets(c(-1, .5, .5)) |> view()
(RepeatedData) |> plotSubsets(c(-1, .5, .5))


(RepeatedData) |> focus(Outcome1, Outcome2) |> estimate() |> graph()


```

## Repeated Summary

```{r}
Outcome1 <- c(N = 10, M = 8.000, SD = 1.414)
Outcome2 <- c(N = 10, M = 11.000, SD = 2.211)
Outcome3 <- c(N = 10, M = 12.000, SD = 2.449)
RepeatedSummary <- construct(Outcome1, Outcome2, Outcome3, class = "wsm")
```

```{r}
Outcome1 <- c(1.000, .533, .385)
Outcome2 <- c(.533, 1.000, .574)
Outcome3 <- c(.385, .574, 1.000)
RepeatedCorr <- construct(Outcome1, Outcome2, Outcome3, class = "cor")
```

```{r}
(RepeatedSummary)
(RepeatedCorr) |> print(digits=5)

(RepeatedSummary) |> class()
(RepeatedSummary) |> print(digits=6,width=11)
(RepeatedSummary) |> describeMoments() |> print(digits=5)

(RepeatedSummary) |> estimateSet() |> print(digits=8,width=12)
(RepeatedSummary) |> plotSet()

(RepeatedSummary) |> focus(Outcome1, Outcome2) |> estimateDifference(RepeatedCorr)
(RepeatedSummary) |> focus(Outcome1, Outcome2) |> plotDifference(RepeatedCorr)

(RepeatedSummary) |> focus(Outcome1, Outcome3) |> estimateComparison(RepeatedCorr)
(RepeatedSummary) |> focus(Outcome1, Outcome3) |> estimateComparison(RepeatedCorr)
(RepeatedSummary) |> focus(Outcome1, Outcome2) |> plotComparison(RepeatedCorr)

(RepeatedSummary) |> estimateContrast(RepeatedCorr, c(-1, .5, .5))

(RepeatedSummary) |> estimateSubsets(RepeatedCorr, c(-1, .5, .5))
(RepeatedSummary) |> plotSubsets(RepeatedCorr, c(-1, .5, .5))

(RepeatedSummary) |> focus(Outcome1, Outcome2) |> estimate(RepeatedCorr)
 |> graph()

```


### Factorial Data

```{r}
FactorA <- c(rep(1, 20), rep(2, 20), rep(3, 20))
FactorA <- factor(FactorA, levels = c(1, 2, 3), labels = c("A1", "A2", "A3"))
FactorB <- c(rep(1, 10), rep(2, 10), rep(1, 10), rep(2, 10), rep(1, 10), rep(2, 10))
FactorB <- factor(FactorB, levels = c(1, 2), labels = c("B1", "B2"))
Outcome <- c(6, 8, 6, 8, 10, 8, 10, 9, 8, 7, 5, 9, 10, 9, 11, 4, 11, 7, 6, 8, 7, 13, 11, 10, 13, 8, 11, 14, 12, 11, 7, 8, 7, 11, 10, 7, 8, 4, 8, 10, 9, 16, 11, 12, 15, 13, 9, 14, 11, 10, 8, 6, 8, 11, 5, 7, 9, 3, 6, 7)
FactorialData <- construct(FactorA, FactorB, Outcome)

```

```{r}
### Split Data

splitData <- function(x, ...) {
  UseMethod("splitData")
}

splitData.data.frame <- function(frame, by, ...) {
  MixedData <- data.frame(by, data)
  SplitData <- split(MixedData[-1], by)
  return(SplitData)
}

splitData.formula <- function(formula, by, ...) {
  Group <- eval(formula[[3]])
  Outcome <- eval(formula[[2]])
  FactorialData <- data.frame(by, Group, Outcome)
  SplitData <- split(FactorialData[-1], by)
  return(SplitData)
}

```

```{r}
(FactorialData) |> focus(Outcome~FactorA) |> splitData(FactorB) -> SplitFactorial
class(SplitFactorial) -> "split.frame"
SplitFactorial


lapply(test.list, FUN=function(x) perm.test(formula=(cover ~ group),data=x)) 
SplitFactorial |> lapply(FUN=function(x) describeMoments(formula=(Outcome~FactorA)))

SplitFactorial |> lapply(function(x) describeMoments(Outcome~FactorA))

SplitFactorial |> lapply(function(x) (Outcome~FactorA) |> describeMoments())
SplitFactorial |> lapply(\(x) (Outcome~FactorA) |> describeMoments())

```

### Factorial Summary

```{r}

combine <- function(..., class = NULL) {
  output <- list(...)
  class(output) <- class
  return(output)
}
```

```{r}
A1 <- c(N = 10, M = 8.000, SD = 1.414)
A2 <- c(N = 10, M = 11.000, SD = 2.211)
A3 <- c(N = 10, M = 12.000, SD = 2.449)
FactorialSummaryB1 <- construct(A1, A2, A3, class = "bsm")
A1 <- c(N = 10, M = 8.000, SD = 2.449)
A2 <- c(N = 10, M = 8.000, SD = 2.000)
A3 <- c(N = 10, M = 7.000, SD = 2.211)
FactorialSummaryB2 <- construct(A1, A2, A3, class = "bsm")
FactorialSummary <- combine(B1 = FactorialSummaryB1, B2 = FactorialSummaryB2, class = "bsl")
```

```{r}
estimateSetMeans.bsl <- function(list, ...) {
  lapply(list, estimateSetMeans, ...)
}

estimateSet(FactorialSummary)

```
