
## Mixed Vignette

This vignette analyzes data from a two-factor mixed design.

```{r}
source("http://raw.githubusercontent.com/cwendorf/easiDev/main/source-easiDev.R")
```

### Data Management

#### Data Entry

```{r}
Factor <- c(1, 1, 1, 1, 2, 2, 2, 2)
Outcome1 <- c(0, 0, 3, 5, 1, 3, 6, 6)
Outcome2 <- c(4, 7, 4, 9, 3, 1, 6, 6)
Outcome3 <- c(4, 9, 6, 9, 3, 3, 6, 8)
Factor <- factor(Factor, levels = c(1, 2), labels = c("Level1", "Level2"))
MixedData <- data.frame(Factor, Outcome1, Outcome2, Outcome3)
```

Data
(Focus and/or Split)
Describe
(Focus and/or Split)
Analyze







```{r}
# This works
(MixedData) |> splitData(Factor) |> describeMoments() |> estimateMeansSet()
```






```{r}

dmb <- function(x, ...) {
  UseMethod("dmb")
}

dmb.data.frame <- function(frame, by, ...) {
  MixedData <- data.frame(by, frame)
  SplitData <- split(MixedData[-1], by)
  results <- lapply(SplitData, describeMoments)
  results
}



```

```{r}

Simple <- data.frame(Outcome1,Outcome2,Outcome3)
(Simple) |> dmb(Factor) |> estimateMeansSet()



```


### Data Entry

This code inputs the variable summaries and creates a summary table.
```{r}
Outcome1 <- c(N = 10, M = 8.000, SD = 1.414)
Outcome2 <- c(N = 10, M = 11.000, SD = 2.211)
Outcome3 <- c(N = 10, M = 12.000, SD = 2.449)
MixedSummaryL1 <- construct(Outcome1, Outcome2, Outcome3, class = "wsm")
Outcome1 <- c(N = 10, M = 8.000, SD = 2.449)
Outcome2 <- c(N = 10, M = 8.000, SD = 2.000)
Outcome3 <- c(N = 10, M = 7.000, SD = 2.211)
MixedSummaryL2 <- construct(Outcome1, Outcome2, Outcome3, class = "wsm")
MixedSummary <- combine(L1 = MixedSummaryL1, L2 = MixedSummaryL2, class = "list")
```

This code creates correlation matrices.
```{r}
Outcome1 <- c(1.000, .533, .385)
Outcome2 <- c(.533, 1.000, .574)
Outcome3 <- c(.385, .574, 1.000)
MixedCorrL1 <- construct(Outcome1, Outcome2, Outcome3, class = "corr")
Outcome1 <- c(1.000, .408, .164)
Outcome2 <- c(.408, 1.000, .553)
Outcome3 <- c(.164, .553, 1.000)
MixedCorrL2 <- construct(Outcome1, Outcome2, Outcome3, class = "corr")
MixedCorr <- combine(L1 = MixedCorrL1, L2 = MixedCorrL2, class = "corr")
```


```{r}
# This works
(MixedSummary) |> describeMoments()
(MixedSummary) |> estimateMeansSet()
```

