---
title: "OneWay Alternative Data Example"
description: >
  This page examines a single-factor between-subjects (one-way) design using raw data input, focusing on comparisons and contrasts.
output: rmarkdown::html_vignette
---

```{r,include=FALSE}
if (!require(easiDev)) {
  if (!require(remotes)) install.packages("remotes")
  remotes::install_github("cwendorf/easiDev")
}
library(easiDev)
```

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 7, comment = NA)
```

## OneWay Vignette

This vignette analyzes data from a one-way between-subjects design.

```{r}
source("http://raw.githubusercontent.com/cwendorf/easiDev/main/source-easiDev.R")
```

```{r,include=FALSE}
devtools::source_gist("8e6e5dc401e3fc1042ef7a030f9d19c7", filename = "revised_toc.R")
thisfile <- knitr::current_input()
revised_toc(thisfile, base_level = 3, toc_depth = 4)
```

---

### One Way Data

```{r}
Factor <- c(rep(1, 10), rep(2, 10), rep(3, 10))
Factor <- factor(Factor, levels = c(1, 2, 3), labels = c("Level1", "Level2", "Level3"))
Outcome <- c(6, 8, 6, 8, 10, 8, 10, 9, 8, 7, 7, 13, 11, 10, 13, 8, 11, 14, 12, 11, 9, 16, 11, 12, 15, 13, 9, 14, 11, 10)
OneWayData <- construct(Factor, Outcome)
```

```{r}
(Outcome~Factor) |> describeMoments()

(Outcome~Factor) |> focus(Level1, Level2, Level3) |> estimateMeans()
(Outcome~Factor) |> focus(Level1, Level2, Level3) |> plotMeans()
(Outcome~Factor) |> focus(Level1, Level2) |> estimateMeans() |> plot()
(Outcome~Factor) |> estimateMeans(contrast=c(-1, .5, .5))
(Outcome~Factor) |> estimateMeans(contrast=c(-1, .5, .5),labels=c("neg","pos")) |> plot(main="Cool",digits=1,xlab="time")
(Outcome~Factor) |> plotMeans(contrast=c(-1, .5, .5),labels=c("neg","pos"))

```

```{r}

(Outcome~Factor) |> describeMoments()
(Outcome~Factor) |> describeMoments() |> estimateMeans(conf.level=.99)
(Outcome~Factor) |> describeMoments() |> plotMeans(conf.level=.99, line=9, rope=c(8,10))

(Outcome~Factor) |> describeMoments() |> focus(Level1, Level2) |> estimateMeans() |> plotIntervals()
(Outcome~Factor) |> describeMoments() |> estimateMeans(contrast=c(-1, .5, .5))
(Outcome~Factor) |> describeMoments() |> estimateMeans(contrast=c(-1, .5, .5),labels=c("neg","pos")) |> plot(main="Cool",digits=1,xlab="time")
(Outcome~Factor) |> describeMoments() |> plotMeans(contrast=c(-1, .5, .5), rope=c(-2,2))

```


### One Way Summary

```{r}
Level1 <- c(N = 10, M = 8.000, SD = 1.414)
Level2 <- c(N = 10, M = 11.000, SD = 2.211)
Level3 <- c(N = 10, M = 12.000, SD = 2.449)
OneWaySummary <- construct(Level1, Level2, Level3, class = "bsm")
```

```{r}
(OneWaySummary)
(OneWaySummary) |> print(digits=4,width=12)

(OneWaySummary) |> estimateMeansSet()
(OneWaySummary) |> plotMeans(line=9,main="title",values=FALSE)
(OneWaySummary) |> focus(Level1, Level2) |> estimateMeans(conf.level=.99, mu =3)
(OneWaySummary) |> focus(Level1, Level2) |> estimateMeans() |> plot(main="title")

(OneWaySummary) |> estimateMeans(contrast=c(-1, .5, .5))
(OneWaySummary) |> plotMeans(contrast=c(-1, .5, .5),digits=6)
(OneWaySummary) |> estimateMeans(contrast=c(-1, .5, .5)) |> plot(main="title",digits=6)

```

