---
title: "Repeated Alternative Data Example"
description: >
  This page examines a single-factor within-subjects (repeated measures) design using raw data input, focusing on comparisons and contrasts.
output: rmarkdown::html_vignette
---

```{r,include=FALSE}
if (!require(easiDev)) {
  if (!require(remotes)) install.packages("remotes")
  remotes::install_github("cwendorf/easiDev")
}
library(easiDev)
```

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 7, comment = NA)
```

## Repeated Vignette

This vignette analyzes data from a single-factor within-subjects design.

```{r}
source("http://raw.githubusercontent.com/cwendorf/easiDev/main/source-easiDev.R")
```

```{r,include=FALSE}
devtools::source_gist("8e6e5dc401e3fc1042ef7a030f9d19c7", filename = "revised_toc.R")
thisfile <- knitr::current_input()
revised_toc(thisfile, base_level = 3, toc_depth = 4)
```

---


```{r}
Outcome1 <- c(6, 8, 6, 8, 10, 8, 10, 9, 8, 7)
Outcome2 <- c(7, 13, 11, 10, 13, 8, 11, 14, 12, 11)
Outcome3 <- c(9, 16, 11, 12, 15, 13, 9, 14, 11, 10)
RepeatedData <- construct(Outcome1, Outcome2, Outcome3)
```

```{r}
(RepeatedData)
(RepeatedData) |> describeMoments() |> view()
(RepeatedData) |> describeMoments() |> print(digits=2,width=10,main="tough")
(RepeatedData) |> describeCorrelations() |> print(digits=6)

(RepeatedData) |> estimateMeans()

(RepeatedData) |> focus(Outcome1, Outcome2) |> estimateMeans() |> print(digits=6,main=c("cool","cooler"))
(RepeatedData) |> focus(Outcome1, Outcome2) |> plotMeans(main="cool",digits=6)
(RepeatedData) |> focus(Outcome1, Outcome2) |> estimateMeans() |> plot(digits=6)

(RepeatedData) |> estimateMeans(contrast = c(-1, .5, .5), conf.level=.99)
(RepeatedData) |> estimateMeans(contrast = c(-1, .5, .5)) |> plot()

```

```{R}
(RepeatedData) |> describeCorrelations() |> print(digits=6)
(RepeatedData) |> estimateCorrelations() |> .deList()

(RepeatedData) |> estimateCorrelations() |> print(digits=6, width=10, main = "cools")
(RepeatedData) |> estimateCorrelations() |> plot()

```

```{r}

(RepeatedData) |> estimateMeans() |> print(digits=0)
```

## Repeated Summary

```{r}
Outcome1 <- c(N = 10, M = 8.000, SD = 1.414)
Outcome2 <- c(N = 10, M = 11.000, SD = 2.211)
Outcome3 <- c(N = 10, M = 12.000, SD = 2.449)
RepeatedSummary <- construct(Outcome1, Outcome2, Outcome3, class = "wsm")
```

```{r}
Outcome1 <- c(1.000, .533, .385)
Outcome2 <- c(.533, 1.000, .574)
Outcome3 <- c(.385, .574, 1.000)
RepeatedCorr <- construct(Outcome1, Outcome2, Outcome3, class = "cor")
```

```{r}
(RepeatedSummary) |> print(digits=6,width=11)
(RepeatedCorr) |> print(digits=5)

(RepeatedSummary) |> describeMoments() |> print(digits=5)
(RepeatedSummary) |> estimateMeans() |> print(digits=8,width=12)
(RepeatedSummary) |> estimateMeans() |> plot(digits=8,width=12)

(RepeatedSummary) |> focus(Outcome1, Outcome2) |> estimateMeans(RepeatedCorr)
(RepeatedSummary) |> focus(Outcome1, Outcome2) |> estimateMeans(RepeatedCorr) |> plot(main="Coolsville")
(RepeatedSummary) |> focus(Outcome1, Outcome2) |> plotMeans(RepeatedCorr)

(RepeatedSummary) |> estimateMeans(RepeatedCorr, contrast = c(-1, .5, .5))
(RepeatedSummary) |> estimateMeans(RepeatedCorr, contrast = c(-1, .5, .5)) |> plot()

```

```{r}
(RepeatedSummary) |> describeMoments() |> estimateMeans()
(RepeatedSummary) |> describeMoments() |> estimateMeans() |> plot()

(RepeatedSummary) |> focus(Outcome1, Outcome2) |> describeMoments() |> estimateMeans(RepeatedCorr)
(RepeatedSummary) |> describeMoments() |> focus(Outcome1, Outcome2) |> estimateMeans(RepeatedCorr)

(RepeatedSummary) |> describeMoments() |> focus(Outcome1, Outcome2) |> estimateMeans(RepeatedCorr) |> plot()
(RepeatedSummary) |> describeMoments() |> focus(Outcome1, Outcome2) |> plotMeans(RepeatedCorr, conf.level= .99, rope=c(-2,2), main = "title")


(RepeatedSummary) |> describeMoments() |> plotMeans(RepeatedCorr, contrast = c(-1, .5, .5))
(RepeatedSummary) |> describeMoments() |> estimateMeans(RepeatedCorr, contrast = c(-1, .5, .5)) |> plot()

```
